name: Nightly SBOM Rescan

on:
  schedule:
    - cron: '0 2 * * *'   # every day 02:00 UTC
  workflow_dispatch:

jobs:
  rescan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download Stored SBOM
      uses: actions/download-artifact@v4
      with:
        name: image-sbom

    - name: Install Grype
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan SBOM
      run: |
        grype sbom:image-sbom.json --fail-on high
